{{- if not (lookup "v1" "ConfigMap" .Release.Namespace "ssl-certificates") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-certificates
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- tpl (.Files.Glob "ssl/*").AsConfig . | nindent 2 }}
{{- end }}