apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongodb
  namespace: ${{inputs.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mongodb
  template:
    metadata:
      labels:
        app: my-mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnamilegacy/mongodb:4.2.14
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
