openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: catalog-controller
    description: Catalog Controller
paths:
  /catalog/api/v1/projects/bulk/create:
    post:
      tags:
        - catalog-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonNode'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Project'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Connection:
      title: Connection
      type: object
      properties:
        connectionType:
          type: string
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: string
        services:
          type: array
          items:
            type: string
        sourceTemplateId:
          type: string
          format: uuid
        systemId:
          type: string
          format: uuid
    Environment:
      title: Environment
      type: object
      properties:
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        graylogName:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        projectId:
          type: string
          format: uuid
        systems:
          type: array
          items:
            $ref: '#/components/schemas/System'
        ssmSolutionAlias:
          type: string
        ssmInstanceAlias:
          type: string
        consulEgressConfigPath:
          type: string
        tags:
          type: array
          items:
            type: string
    JsonNode:
      title: JsonNode
      type: object
    ParametersGettingVersion:
      title: ParametersGettingVersion
      type: object
      properties:
        headers:
          type: string
        parameters:
          type: string
        parsingType:
          type: string
          enum:
            - JSONPATH
            - NONE
            - REGEXP
        parsingValue:
          type: string
        type:
          type: string
          enum:
            - BY_HTTP_ENDPOINT
            - BY_HTTP_ENDPOINT_BASIC_AUTH
            - BY_KUBERNETES_CONFIGMAP
            - BY_KUBERNETES_IMAGES
            - BY_OPENSHIFT_CONFIGURATION
            - BY_SHELL_SCRIPT
            - BY_SQL_QUERY
            - BY_SSM
    Project:
      title: Project
      type: object
      properties:
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        environments:
          type: array
          items:
            $ref: '#/components/schemas/Environment'
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        shortName:
          type: string
    ServerItf:
      title: ServerItf
      type: object
      properties:
        name:
          type: string
        url:
          type: string
    System:
      title: System
      type: object
      properties:
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        dateOfCheckVersion:
          type: integer
          format: int64
        dateOfLastCheck:
          type: integer
          format: int64
        description:
          type: string
        environmentIds:
          type: array
          items:
            $ref: '#/components/schemas/Environment'
        environments:
          type: array
          items:
            $ref: '#/components/schemas/Environment'
        externalId:
          type: string
          format: uuid
        externalName:
          type: string
        id:
          type: string
          format: uuid
        linkToSystemId:
          type: string
          format: uuid
        mergeByName:
          type: boolean
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        parametersGettingVersion:
          $ref: '#/components/schemas/ParametersGettingVersion'
        parentSystemId:
          type: string
          format: uuid
        serverITF:
          $ref: '#/components/schemas/ServerItf'
        status:
          type: string
          enum:
            - FAIL
            - NOTHING
            - PASS
            - WARN
        systemCategory:
          type: object #$ref: '#/components/schemas/SystemCategory'
        systemCategoryId:
          type: string
          format: uuid
        version:
          type: string
    SystemCategory:
      title: SystemCategory
      type: object
      properties:
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
