openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: subscriber-controller
    description: Subscriber Controller
paths:
  /api/subscribers:
    get:
      tags:
        - subscriber-controller
      summary: getAll
      operationId: getAll
      parameters:
        - name: full
          in: query
          description: full
          required: false
          style: form
          schema:
            type: boolean

      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscriber'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - subscriber-controller
      summary: update
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriberImpl'
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - subscriber-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriberImpl'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Subscriber'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/subscribers/{subscriberId}':
    get:
      tags:
        - subscriber-controller
      summary: getsubscriber
      operationId: getsubscriber
      parameters:
        - name: subscriberId
          in: path
          description: subscriberId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: full
          in: query
          description: full
          required: false
          style: form
          schema:
            type: boolean

      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Subscriber'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - subscriber-controller
      summary: delete
      operationId: delete
      parameters:
        - name: subscriberId
          in: path
          description: subscriberId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Subscriber:
      title: Subscriber
      type: object
      properties:
        host:
          type: string
        hostStatus:
          type: integer
          format: int32
        id:
          type: string
          format: uuid
        name:
          type: string
        notificationURL:
          type: string
        registrationDate:
          type: integer
          format: int64
        signature:
          type: string
        subscriberType:
          type: integer
          format: int32
        subscriptions:
          type: array
          items:
            type: object #type: object #$ref: '#/components/schemas/Subscription'
        tagList:
          type: string
    SubscriberImpl:
      title: SubscriberImpl
      type: object
      properties:
        host:
          type: string
        hostStatus:
          type: integer
          format: int32
        id:
          type: string
          format: uuid
        name:
          type: string
        notificationURL:
          type: string
        registrationDate:
          type: integer
          format: int64
        signature:
          type: string
        subscriberType:
          type: integer
          format: int32
        subscriptions:
          type: array
          items:
            type: object #$ref: '#/components/schemas/Subscription'
        tagList:
          type: string
    Subscription:
      title: Subscription
      type: object
      properties:
        environmentId:
          type: string
          format: uuid
        id:
          type: string
          format: uuid
        lastUpdated:
          type: integer
          format: int64
        projectId:
          type: string
          format: uuid
        status:
          type: integer
          format: int32
        subscriberId:
          type: object #$ref: '#/components/schemas/Subscriber'
        subscriptionType:
          type: integer
          format: int32
        systemId:
          type: string
          format: uuid
        updateEvents:
          type: array
          items:
            $ref: '#/components/schemas/UpdateEvent'
    UpdateEvent:
      title: UpdateEvent
      type: object
      properties:
        entityId:
          type: string
          format: uuid
        entityType:
          type: string
        lastEventDate:
          type: integer
          format: int64
        status:
          type: integer
          format: int32
        subscriptionId:
          type: string
          format: uuid
        tagList:
          type: string
