openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: environment-category-controller
    description: Environment Category Controller
paths:
  /api/environment-categories:
    get:
      tags:
        - environment-category-controller
      summary: getAll
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnvironmentCategory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - environment-category-controller
      summary: update
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentCategoryImpl'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EnvironmentCategory'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - environment-category-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentCategoryImpl'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EnvironmentCategory'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/environment-categories/{environmentCategoryId}':
    get:
      tags:
        - environment-category-controller
      summary: get
      operationId: get
      parameters:
        - name: environmentCategoryId
          in: path
          description: environmentCategoryId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EnvironmentCategory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - environment-category-controller
      summary: delete
      operationId: delete
      parameters:
        - name: environmentCategoryId
          in: path
          description: environmentCategoryId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    EnvironmentCategory:
      title: EnvironmentCategory
      type: object
      properties:
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        tagList:
          type: string
    EnvironmentCategoryImpl:
      title: EnvironmentCategoryImpl
      type: object
      properties:
        created:
          type: integer
          format: int64
        createdBy:
          type: string
          format: uuid
        description:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: integer
          format: int64
        modifiedBy:
          type: string
          format: uuid
        name:
          type: string
        tagList:
          type: string
