openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: version-controller
    description: Version Controller
paths:
  /api/version:
    get:
      tags:
        - version-controller
      summary: getVersion
      operationId: getVersion
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components: {}
