openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: database-directory-controller
    description: Database Directory Controller
paths:
  /api/database-directory:
    get:
      tags:
        - database-directory-controller
      summary: getAll
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DatabaseDirectory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/database-directory/{name}':
    get:
      tags:
        - database-directory-controller
      summary: getName
      operationId: getName
      parameters:
        - name: name
          in: path
          description: name
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DatabaseDirectory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    DatabaseDirectory:
      title: DatabaseDirectory
      type: object
      properties:
        name:
          type: string
        urlFormat:
          type: string
