openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: "1.0"
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: alert-controller
    description: Alert Controller
paths:
  /api/alerts:
    get:
      tags:
        - alert-controller
      summary: getAll
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alert'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/alerts/create:
    put:
      tags:
        - alert-controller
      summary: update
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertImpl'
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - alert-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertImpl'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Alert'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/alerts/{alertId}':
    get:
      tags:
        - alert-controller
      summary: getAlert
      operationId: getAlert
      parameters:
        - name: alertId
          in: path
          description: alertId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Alert'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - alert-controller
      summary: delete
      operationId: delete
      parameters:
        - name: alertId
          in: path
          description: alertId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Alert:
      title: Alert
      type: object
      properties:
        created:
          type: integer
          format: int64
        id:
          type: string
          format: uuid
        name:
          type: string
        parameters:
          type: string
        shortDescription:
          type: string
        status:
          type: integer
          format: int32
        subscriberId:
          type: string
          format: uuid
        tagList:
          type: string
    AlertImpl:
      title: AlertImpl
      type: object
      properties:
        created:
          type: integer
          format: int64
        id:
          type: string
          format: uuid
        name:
          type: string
        parameters:
          type: string
        shortDescription:
          type: string
        status:
          type: integer
          format: int32
        subscriberId:
          type: string
          format: uuid
        tagList:
          type: string
