openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: datasets-controller
    description: Datasets Controller
paths:
  '/catalog/api/v1/datasets/list/{dataSetListId}':
    delete:
      tags:
        - datasets-controller
      summary: deleteList
      operationId: deleteList
      parameters:
        - name: dataSetListId
          in: path
          description: dataSetListId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/catalog/api/v1/datasets/{dataSetId}':
    delete:
      tags:
        - datasets-controller
      summary: delete
      operationId: delete
      parameters:
        - name: dataSetId
          in: path
          description: dataSetId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components: {}