openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: entity-versioning-controller
    description: Entity Versioning Controller
paths:
  '/catalog/api/v1/entityversioning/{projectId}/{itemType}/{uuid}':
    get:
      tags:
        - entity-versioning-controller
      summary: getEntitiesByVersion
      operationId: getEntitiesByVersion
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: itemType
          in: path
          description: itemType
          required: true
          style: simple
          schema:
            type: string
        - name: uuid
          in: path
          description: uuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: versions
          in: query
          description: versions
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompareEntityResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    AbstractEntityVersioning:
      title: AbstractEntityVersioning
      type: object
      properties:
        description:
          type: string
        modifiedBy:
          type: string
        modifiedWhen:
          type: string
          format: date-time
        name:
          type: string
    CompareEntityResponse:
      title: CompareEntityResponse
      type: object
      properties:
        compareEntity:
          $ref: '#/components/schemas/AbstractEntityVersioning'
        revision:
          type: string
