openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: log-collector-condition-controller
    description: Log Collector Condition Controller
paths:
  /catalog/api/v1/logcollectorconditions:
    put:
      tags:
        - log-collector-condition-controller
      summary: update
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogCollectorCondition'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - log-collector-condition-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogCollectorCondition'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LogCollectorCondition'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/catalog/api/v1/logcollectorconditions/{uuid}':
    delete:
      tags:
        - log-collector-condition-controller
      summary: delete
      operationId: delete
      parameters:
        - name: uuid
          in: path
          description: uuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LogCollectorCondition'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    LogCollectorCondition:
      title: LogCollectorCondition
      type: object
      properties:
        description:
          type: string
        name:
          type: string
        resultJsonPath:
          type: string
        searchCondition:
          type: string
        searchPath:
          type: string
        testPlanId:
          type: string
          format: uuid
        uuid:
          type: string
          format: uuid
