openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: execution-history-controller
    description: Execution History Controller
paths:
  /api/execution-history/testcase/{testCaseId}/executions:
    post:
      tags:
        - execution-history-controller
      summary: getTestCaseExecutions
      operationId: getTestCaseExecutions
      parameters:
        - name: testCaseId
          in: path
          description: test case id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TestCaseExecutionHistorySearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseExecutionHistory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    TestCaseExecutionHistorySearchRequest:
      title: TestCaseExecutionHistorySearchRequest
      type: object
      properties:
        testingStatuses:
          type: array
          items:
            $ref: '#/components/schemas/TestingStatus'
        failureReasons:
          type: array
          items:
            type: string
            format: uuid
        analyzedByQa:
          type: boolean
        environments:
          type: array
          items:
            type: string
            format: uuid
        executors:
          type: array
          items:
            type: string
            format: uuid
        startDate:
          type: string
          format: 'date-time'
        finishDate:
          type: string
          format: 'date-time'
    TestingStatus:
      type: string
      enum:
        - STOPPED
        - FAILED
        - WARNING
        - PASSED
        - SKIPPED
        - BLOCKED
        - NOT_STARTED
        - UNKNOWN
    TestCaseExecutionHistory:
      title: TestCaseExecutionHistory
      type: object
      properties:
        testCaseName:
          type: string
        totalCount:
          type: integer
          format: int64
        executions:
          type: array
          items:
            $ref: '#/components/schemas/TestCaseExecution'
    TestCaseExecution:
      title: TestCaseExecution
      type: object
      properties:
        projectId:
          type: string
          format: uuid
        executionRequestId:
          type: string
          format: uuid
        executionRequestName:
          type: string
        testRunId:
          type: string
          format: uuid
        testingStatus:
          $ref: '#/components/schemas/TestingStatus'
        analyzedByQa:
          type: boolean
        startDate:
          type: string
          format: 'date-time'
        finishDate:
          type: string
          format: 'date-time'
        duration:
          type: integer
          format: int64
        passedRate:
          type: integer
          format: int32
        warningRate:
          type: integer
          format: int32
        failedRate:
          type: integer
          format: int32
        executorId:
          type: string
          format: uuid
        executorName:
          type: string
        filteredByLabelsIds:
          type: array
          items:
            type: string
            format: uuid
        filteredByLabels:
          type: array
          items:
            $ref: '#/components/schemas/Label'
        environmentId:
          type: string
          format: uuid
        environmentName:
          type: string
        failReason:
          type: string
    Label:
      title: Label
      type: object
      properties:
        labelId:
          type: string
          format: uuid
        labelName:
          type: string