openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: fail-pattern-controller
    description: Fail Pattern Controller
paths:
  /api/failpatterns:
    put:
      tags:
        - fail-pattern-controller
      summary: save
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailPattern'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailPattern'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - fail-pattern-controller
      summary: create
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailPattern'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailPattern'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/failpatterns/search:
    post:
      tags:
        - fail-pattern-controller
      summary: search
      operationId: search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailPatternSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailPatternPageResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/failpatterns/check:
    put:
      tags:
        - fail-pattern-controller
      summary: check
      operationId: check
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailPatternCheckRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/failpatterns/project/{projectId}':
    get:
      tags:
        - fail-pattern-controller
      summary: getAllByProject
      operationId: getAllByProject
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: startIndex
          in: query
          description: startIndex
          required: true
          style: form
          schema:
            type: integer
            format: int32
        - name: endIndex
          in: query
          description: endIndex
          required: true
          style: form
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailPatternPageResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/failpatterns/{id}':
    get:
      tags:
        - fail-pattern-controller
      summary: getById
      operationId: getById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailPatternResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - fail-pattern-controller
      summary: delete
      operationId: delete
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/api/failpatterns/find-name-pagination':
    post:
      tags:
        - fail-pattern-controller
      summary: getAllNamesWithPagination
      operationId: getAllNamesWithPagination
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaginationSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseEntityPaginationResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/failpatterns/issues/find-name-pagination':
    post:
      tags:
        - fail-pattern-controller
      summary: getAllIssuesWithPagination
      operationId: getAllIssuesWithPagination
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaginationSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseEntityPaginationResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/failpatterns/fail-reasons/find-name-pagination':
    post:
      tags:
        - fail-pattern-controller
      summary: getAllFailReasonsWithPagination
      operationId: getAllFailReasonsWithPagination
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaginationSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseEntityPaginationResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    FailPattern:
      title: FailPattern
      type: object
      properties:
        failReasonId:
          type: string
          format: uuid
        jiraTickets:
          type: array
          items:
            type: string
        message:
          type: string
        name:
          type: string
        patternDescription:
          type: string
        priority:
          $ref: '#/components/schemas/Priority'
        projectId:
          type: string
          format: uuid
        rule:
          type: string
        uuid:
          type: string
          format: uuid
    Priority:
      type: string
      enum:
        - BLOCKER
        - CRITICAL
        - LOW
        - MAJOR
        - NORMAL
    FailPatternPageResponse:
      title: FailPatternPageResponse
      type: object
      properties:
        failPatterns:
          type: array
          items:
            $ref: '#/components/schemas/FailPatternResponse'
        totalCount:
          type: integer
          format: int32
    FailPatternResponse:
      title: FailPatternResponse
      type: object
      properties:
        failReason:
          $ref: '#/components/schemas/RamObjectResponse'
        jiraTickets:
          type: array
          items:
            type: string
        message:
          type: string
        name:
          type: string
        patternDescription:
          type: string
        priority:
          $ref: '#/components/schemas/Priority'
        project:
          $ref: '#/components/schemas/RamObjectResponse'
        rule:
          type: string
        uuid:
          type: string
          format: uuid
    RamObjectResponse:
      title: RamObjectResponse
      type: object
      properties:
        name:
          type: string
        uuid:
          type: string
          format: uuid
    FailPatternCheckRequest:
      title: FailPatternCheckRequest
      type: object
      properties:
        message:
          type: string
        rule:
          type: string
    PaginationSearchRequest:
      title: PaginationSearchRequest
      type: object
      properties:
        name:
          type: string
        projects:
          type: array
          items:
            type: string
            format: uuid
        sort:
          type: string
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
    BaseEntityPaginationResponse:
      title: BaseEntityPaginationResponse
      type: object
      properties:
        entities:
          items:
            $ref: '#/components/schemas/BaseEntityResponse'
        totalCount:
          type: integer
          format: int32
        lastPage:
          type: boolean
    BaseEntityResponse:
      title: BaseEntityResponse
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    FailPatternSearchRequest:
      title: FailPatternSearchRequest
      type: object
      properties:
        names:
          type: array
          items:
            format: string
        priorities:
          type: array
          items:
            format: string
        message:
          type: string
        issues:
          type: array
          items:
            format: string
        projects:
          type: array
          items:
            format: uuid
        failReasons:
          type: array
          items:
            format: uuid