openapi: 3.0.3
info:
  title: 'jira-integration-controller'
  description: 'Jira Integration API'
  version: '1.0'
tags:
  - name: jira-integration-controller
    description: Jira Integration Controller
paths:
  '/api/executionrequests/{id}/testruns/infoForJira':
    get:
      tags:
        - jira-integration-controller
      description:
        Requests data for test runs by execution request id to propagate in JIRA
      summary: getTestRunsForJiraInfoByExecutionRequest
      operationId: getTestRunsForJiraInfoByExecutionRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestRunToJiraInfo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/testruns/infoForJira:
    post:
      tags:
        - jira-integration-controller
      description:
        Requests data for test runs by list of id to propogate in JIRA
      summary: getTestRunsForJiraInfo
      operationId: getTestRunsForJiraInfo
      requestBody:
        description: ids
        content:
          application/json:
            schema:
              title: ids
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestRunToJiraInfo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/testruns/infoForRefreshing:
    post:
      tags:
        - jira-integration-controller
      description:
        Requests data for test runs by list of id to refresh info from JIRA
      summary: getTestRunsForRefreshFromJira
      operationId: getTestRunsForRefreshFromJira
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestRunForRefreshFromJira'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    TestRunToJiraInfo:
      title: TestRunToJiraInfo
      type: object
      properties:
        environmentInfo:
          type: string
        executionRequestId:
          type: string
          format: uuid
        jiraTicket:
          type: string
        lastRun:
          type: boolean
        name:
          type: string
        testCaseId:
          type: string
          format: uuid
        testRunAtpLink:
          type: string
        testingStatus:
          type: string
        uuid:
          type: string
          format: uuid
    TestRunForRefreshFromJira:
      title: TestRunForRefreshFromJira
      type: object
      properties:
        jiraTicket:
          type: string
        lastRun:
          type: boolean
        name:
          type: string
        testCaseId:
          type: string
          format: uuid
        uuid:
          type: string
          format: uuid
