openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: rerun-controller
    description: Rerun Controller
paths:
  /api/executionrequests/runrerun:
    post:
      tags:
        - rerun-controller
      summary: runRerunExecutionRequests
      operationId: runRerunExecutionRequests
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/executionrequests/v0/runrerun:
    post:
      tags:
        - rerun-controller
      summary: runRerunExecutionRequestsOld
      operationId: runRerunExecutionRequestsOld
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: true
  /api/executionrequests/rerun/filtering:
    post:
      tags:
        - rerun-controller
      summary: rerunByFilter
      operationId: rerunByFilter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RerunRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/testruns/runrerun:
    post:
      tags:
        - rerun-controller
      summary: runRerun
      operationId: runRerun
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    RerunRequest:
      title: RerunRequest
      type: object
      properties:
        executionRequestId:
          type: string
          format: uuid
        statuses:
          type: array
          items:
            $ref: '#/components/schemas/TestingStatus'
    TestingStatus:
      type: string
      enum:
        - STOPPED
        - FAILED
        - WARNING
        - PASSED
        - SKIPPED
        - BLOCKED
        - NOT_STARTED
        - UNKNOWN
