openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: attachment-controller
    description: Attachment Controller
paths:
  '/attachment/attributeId/{attributeId}/dataset/{datasetId}':
    get:
      tags:
        - attachment-controller
      summary: getAttachmentByAttributeIdAndDatasetId
      operationId: getAttachmentByAttributeIdAndDatasetId
      parameters:
        - name: attributeId
          in: path
          description: attributeId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: datasetId
          in: path
          description: datasetId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - attachment-controller
      summary: uploadByAttributeIdAndDatasetId
      operationId: uploadByAttributeIdAndDatasetId
      parameters:
        - name: attributeId
          in: path
          description: attributeId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: datasetId
          in: path
          description: datasetId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: type
          in: query
          description: type
          required: true
          style: form
          schema:
            type: string
        - name: fileName
          in: query
          description: fileName
          required: true
          style: form
          schema:
            type: string
        - name: dataSetListId
          in: query
          description: dataSetListId
          required: false
          style: form
          schema:
            type: string
            format: uuid
        - name: modifiedWhen
          in: query
          description: modifiedWhen
          required: false
          style: form
          schema:
            type: integer
            format: int64
        - name: file
          in: query
          description: file
          required: true
          style: form
          schema:
            type: string
            format: binary            
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/FileData'
        '201':
          description: Created
        '226':
          description: IM Used
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - attachment-controller
      summary: deleteByAttributeIdAndDatasetId
      operationId: deleteByAttributeIdAndDatasetId
      parameters:
        - name: attributeId
          in: path
          description: attributeId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: datasetId
          in: path
          description: datasetId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/attachment/{parameterUuid}':
    get:
      tags:
        - attachment-controller
      summary: getAttachmentByParameterId
      operationId: getAttachmentByParameterId
      parameters:
        - name: parameterUuid
          in: path
          description: parameterUuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - attachment-controller
      summary: uploadByParameterId
      operationId: uploadByParameterId
      parameters:
        - name: parameterUuid
          in: path
          description: parameterUuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: type
          in: query
          description: type
          required: true
          style: form
          schema:
            type: string
        - name: fileName
          in: query
          description: fileName
          required: true
          style: form
          schema:
            type: string
        - name: file
          in: query
          description: file
          required: true
          style: form
          schema:
            type: string
            format: binary
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/FileData'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - attachment-controller
      summary: deleteByParameterId
      operationId: deleteByParameterId
      parameters:
        - name: parameterUuid
          in: path
          description: parameterUuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    FileData:
      title: FileData
      type: object
      properties:
        contentType:
          type: string
        fileName:
          type: string
        fileType:
          type: string
        parameterUuid:
          type: string
          format: uuid
        url:
          type: string
