openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: health-check-controller
    description: Health Check Controller
paths:
  /health/visibility_areas_list:
    get:
      tags:
        - health-check-controller
      summary: getTestVisibilityAreasList
      operationId: getTestVisibilityAreasList
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: string
                  format: uuid
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components: {}
