openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: label-filter-controller
    description: Label Filter Controller
paths:
  /filter/create:
    post:
      tags:
        - label-filter-controller
      summary: Create new filter
      operationId: createFilter
      parameters:
        - name: name
          in: query
          description: name
          required: true
          style: form
          schema:
            type: string
        - name: vaId
          in: query
          description: vaId
          required: true
          style: form
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: array
                items:
                  type: string
                  format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Filter'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /filter/delete:
    delete:
      tags:
        - label-filter-controller
      summary: Delete filter by id
      operationId: delete
      parameters:
        - name: filterId
          in: query
          description: filterId
          required: true
          style: form
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /filter/get:
    get:
      tags:
        - label-filter-controller
      summary: Returns all filter under visibility area
      operationId: getFilters
      parameters:
        - name: vaId
          in: query
          description: vaId
          required: false
          style: form
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Filter'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /filter/update:
    put:
      tags:
        - label-filter-controller
      summary: Update filter name and filter labels
      operationId: update
      parameters:
        - name: name
          in: query
          description: name
          required: false
          style: form
          schema:
            type: string
        - name: filterId
          in: query
          description: filterId
          required: false
          style: form
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: array
                items:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Filter:
      title: Filter
      required:
        - id
        - name
      type: object
      properties:
        dataSetLabels:
          type: array
          items:
            type: string
            format: uuid
        dataSetListLabels:
          type: array
          items:
            type: string
            format: uuid
        id:
          type: string
          format: uuid
        name:
          type: string
        visibilityAreaId:
          type: string
          format: uuid
