openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: test-plan-controller
    description: Test Plan Controller
paths:
  '/testplan/va/{vaId}':
    get:
      tags:
        - test-plan-controller
      summary: Returns all test plans for selected visibility area.
      operationId: getTestPlans
      parameters:
        - name: vaId
          in: path
          description: vaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestPlan'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - test-plan-controller
      summary: Creates new Test Plan with name provided.
      operationId: create
      parameters:
        - name: vaId
          in: path
          description: vaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: name
          in: query
          description: name
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - test-plan-controller
      summary: Deletes Test Plan with provided name.
      operationId: delete
      parameters:
        - name: vaId
          in: path
          description: vaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: name
          in: query
          description: name
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/testplan/{testPlanId}/dsl':
    get:
      tags:
        - test-plan-controller
      summary: Returns dataSetLists with selected Test Plan
      operationId: getDataSetListsUnderTestPlan
      parameters:
        - name: testPlanId
          in: path
          description: testPlanId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSetListIdNameLabelsTestPlanView'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Attribute:
      title: Attribute
      required:
        - dataSetList
        - id
        - name
        - type
      type: object
      properties:
        dataSetList:
          description: parent
          $ref: '#/components/schemas/DataSetList'
        dataSetListReference:
          description: for dsl type
          $ref: '#/components/schemas/DataSetList'
        id:
          type: string
          format: uuid
        listValues:
          type: array
          description: for list type
          items:
            $ref: '#/components/schemas/ListValue'
        name:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
        type:
          $ref: '#/components/schemas/AttributeType'
    DataSet:
      title: DataSet
      type: object
    DataSetList:
      title: DataSetList
      required:
        - id
        - name
        - visibilityArea
      type: object
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        createdBy:
          type: string
          format: uuid
        createdWhen:
          type: string
          format: date-time
        dataSets:
          type: array
          items:
            $ref: '#/components/schemas/DataSet'
        id:
          type: string
          format: uuid
        labels:
          type: array
          items:
            $ref: '#/components/schemas/Label'
        modifiedBy:
          type: string
          format: uuid
        modifiedWhen:
          type: string
          format: date-time
        name:
          type: string
        testPlan:
          $ref: '#/components/schemas/TestPlan'
        visibilityArea:
          description: parent
          $ref: '#/components/schemas/VisibilityArea'
    DataSetListIdNameLabelsTestPlanView:
      title: DataSetListIdNameLabelsTestPlanView
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        labels:
          type: array
          items:
            $ref: '#/components/schemas/LabelIdNameLabelsTestPlanView'
        name:
          type: string
        testPlan:
          $ref: '#/components/schemas/TestPlanIdNameLabelsTestPlanView'
    FileData:
      title: FileData
      type: object
      properties:
        contentType:
          type: string
        fileName:
          type: string
        fileType:
          type: string
        parameterUuid:
          type: string
          format: uuid
        url:
          type: string
    Label:
      title: Label
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    LabelIdNameLabelsTestPlanView:
      title: LabelIdNameLabelsTestPlanView
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    ListValue:
      title: ListValue
      required:
        - attribute
        - id
        - name
      type: object
      properties:
        attribute:
          description: parent
          $ref: '#/components/schemas/Attribute'
        id:
          type: string
          format: uuid
        name:
          type: string
    Parameter:
      title: Parameter
      required:
        - attribute
        - dataSet
        - id
      type: object
      properties:
        attribute:
          description: parent
          $ref: '#/components/schemas/Attribute'
        dataSet:
          description: parent
          $ref: '#/components/schemas/DataSet'
        dataSetReference:
          description: for attribute with dsl type
          $ref: '#/components/schemas/DataSet'
        fileData:
          $ref: '#/components/schemas/FileData'
        id:
          type: string
          format: uuid
        listValue:
          description: for attribute with list type
          $ref: '#/components/schemas/ListValue'
        text:
          type: string
          description: for attribute with text type
    TestPlan:
      title: TestPlan
      required:
        - id
        - name
        - visibilityArea
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        visibilityArea:
          $ref: '#/components/schemas/VisibilityArea'
    TestPlanIdNameLabelsTestPlanView:
      title: TestPlanIdNameLabelsTestPlanView
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    VisibilityArea:
      title: VisibilityArea
      required:
        - id
        - name
      type: object
      properties:
        dataSetLists:
          type: array
          items:
            $ref: '#/components/schemas/DataSetList'
        id:
          type: string
          format: uuid
        name:
          type: string
    AttributeType:
      type: string
      enum:
        - CHANGE
        - DSL
        - ENCRYPTED
        - FILE
        - LIST