openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: user-controller
    description: User Controller
paths:
  /user/current/settings:
    get:
      tags:
        - user-controller
      summary: Returns current user settings.
      operationId: getUserSettings
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserSettings'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    UserSettings:
      title: UserSettings
      type: object
      properties:
        isSortEnabled:
          type: boolean
