openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: visibility-area-controller
    description: Visibility Area Controller
paths:
  /va:
    get:
      tags:
        - visibility-area-controller
      summary: Returns all visibility areas.
      operationId: getVisibilityAreas
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VisibilityAreaFlatModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - visibility-area-controller
      summary: Creates new visibility area with provided name and order.
      operationId: create
      parameters:
        - name: name
          in: query
          description: name
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                format: uuid
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /va/sorted:
    get:
      tags:
        - visibility-area-controller
      summary: Returns all visibility areas sorted by name.
      operationId: getVisibilityAreasSorted
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VisibilityAreaFlatModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/va/{visibilityAreaId}':
    post:
      tags:
        - visibility-area-controller
      summary: Renames selected VA.
      operationId: rename
      parameters:
        - name: visibilityAreaId
          in: path
          description: visibilityAreaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: name
          in: query
          description: name
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: boolean
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - visibility-area-controller
      summary: Deletes selected VA.
      operationId: delete
      parameters:
        - name: visibilityAreaId
          in: path
          description: visibilityAreaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/va/{visibilityAreaId}/copyTo':
    post:
      tags:
        - visibility-area-controller
      summary: Copy DSL with name provided.
      operationId: copyToVisibilityArea
      parameters:
        - name: visibilityAreaId
          in: path
          description: visibilityAreaId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: uuid
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    VisibilityAreaFlatModel:
      title: VisibilityAreaFlatModel
      type: object
      properties:
        dataSetLists:
          type: array
          items:
            type: string
            format: uuid
        id:
          type: string
          format: uuid
        name:
          type: string
