/*
 * # Copyright 2024-2025 NetCracker Technology Corporation
 * #
 * # Licensed under the Apache License, Version 2.0 (the "License");
 * # you may not use this file except in compliance with the License.
 * # You may obtain a copy of the License at
 * #
 * #      http://www.apache.org/licenses/LICENSE-2.0
 * #
 * # Unless required by applicable law or agreed to in writing, software
 * # distributed under the License is distributed on an "AS IS" BASIS,
 * # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * # See the License for the specific language governing permissions and
 * # limitations under the License.
 */

package org.qubership.atp.ram.service.mail;

public interface MailConstants {

    String HEADER_ER_REPORT = "<html dir=\"ltr\"><head>\n"
            + "<style>\n"
            + "<!--\n"
            + ".Investigation\n"
            + "\t{background-color:#836FFF}\n"
            + ".Error\n"
            + "\t{background-color:#836FFF}\n"
            + ".Environment\n"
            + "\t{background-color:#F4A460}\n"
            + ".EnvironmentIssue\n"
            + "\t{background-color:#F4A460}\n"
            + ".AT\n"
            + "\t{background-color:#87CEFA}\n"
            + ".Performance\n"
            + "\t{background-color:#FFFF00}\n"
            + ".Design\n"
            + "\t{background-color:#32CD32}\n"
            + ".Solution\n"
            + "\t{background-color:#FF0000}\n"
            + ".summaryParameters\n"
            + "\t{padding:0px 4px 0px 4px; font-size:10pt;}\n"
            + ".statusPadding\n"
            + "\t{padding-top:4px;padding-bottom:4px;}\n"
            + "-->\n"
            + "</style><style>\n"
            + "<!--\n"
            + ".product_row\n"
            + "\t{display:block}\n"
            + ".root_causes td\n"
            + "\t{padding: 2px}\n"
            + "-->\n"
            + "</style>\n"
            + "<style type=\"text/css\" id=\"owaParaStyle\"></style><style type=\"text/css\" id=\"owaTempEditStyle\">"
            + "</style></head>\n"
            + "<body fpstyle=\"1\" ocsi=\"1\" style=\"font-family:Calibri, Helvetica, sans-serif\">\n"
            + "\n"
            + "<h4><b>Execution Date: </b>${START_DATE}</h4>\n"
            + "<h4><b>ER Link: </b>${RAM_ER_LINK}</h4>\n"
            //+ "<h4><b>Compare with: </b>${COMPARE_LINK}<br></h4>\n"
            + "${CI_JOB_URL}";

    String ROOT_CAUSES_STATISTICS = "<h3>Root Causes Statistics</h3>\n"
            + "<table class='root_causes' border='1' cellpadding='2' cellspacing='0' style='background:#F6FFF2'>\n"
            + "<body>\n"
            + "<tr style='background:#E3FFE6'>"
            + "<td rowspan='2' style='width:15px'><b>#</b></td>\n"
            + "<td rowspan='2' style='width:auto'><b>Start Date</b></td>\n"
            + "<td rowspan='2' style='width:auto'><b>Execution Request</b></td>\n"
            + "${HEADER_ROOT_CAUSE}\n"
            + "</tr>\n"
            + "<tr>\n"
            + "<td style='width:15px'>1</td>\n"
            + "<td style='width:auto'>${START_DATE}</td>\n"
            + "<td style='width:auto'>${ER_NAME}</td>\n"
            + "${TD_WITH_COUNT_AND_RATE}\n"
            + "</tr>\n"
            + "<tr\n>"
            + "${TD_WITH_PREV_COUNT_AND_RATE}\n"
            + "</tr>\n"
            + "</body>\n"
            + "</table><br>\n";

    String SUMMARY_TABLE_TEMPLATE = ""
            + "<h3>Summary</h3>\n"
            + "<div style=\"border:solid; border-width:1px; border-color:#474747\">\n"
            + "<table class=\"MsoNormalTable\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" "
            + "style=\"width:100.0%; background:#F6FFF2\">\n"
            + "<tbody>\n"
            + "<tr style=\"background:#E3FFE6\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">"
            + "Execution Status:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters statusPadding\">\n"
            + "<p class=\"MsoNormal\"><span style=\"font-size:12pt;\"><span id=\"fullExecStatus\" "
            + "style=\"font-size:16px; border:1px solid black;"
            + " background:${EXECUTION_RESULT_COLOR}; color:black; display:inline-block; font-size:16px\">&nbsp;&zwnj;"
            + "&nbsp;&zwnj;&nbsp;"
            + "&zwnj;&nbsp;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&nbsp;&zwnj;&nbsp;</span>&nbsp;"
            + "${EXECUTION_RESULT}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Start Time:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${START_DATE}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenarios:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${TR_COUNT}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTIONS_COUNT}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "<tr style=\"\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Server:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${QA_HOST}</a>\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">End time:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${FINISH_DATE}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenarios passed:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${TR_PASSED}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions passed:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTION_PASSED}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "<tr style=\"background:#E3FFE6\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Build:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${SOLUTION_BUILD}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Duration:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${DURATION}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenarios failed:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${TR_FAILED}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions failed:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTION_FAILED}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "<tr style=\"\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Browser:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span></span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Threads:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>1\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenarios with warnings:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${TR_WARNING}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions with warnings:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTION_WARNING}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "<tr style=\"background:#E3FFE6\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenario's failed rate:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${FAIL_RATE_FORMULA}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenario's passed rate:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${PASS_RATE_FORMULA}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenario's with errors:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${TR_ERROR}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions with errors:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTION_ERROR}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "<tr style=\"\">\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenario error's rate:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ERROR_RATE_FORMULA}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Scenario warning's rate:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${WARN_RATE_FORMULA}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm; min-width:50px\"></td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm; min-width:50px\"></td>\n"
            + "<td style=\"padding:0cm 0cm 0cm 0cm\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:12pt;\">Actions failed rate:</span>\n"
            + "</b></p>\n"
            + "</td>\n"
            + "<td class=\"summaryParameters\">\n"
            + "<p class=\"MsoNormal\"><span>${ACTION_FAIL_RATE}\n"
            + "</span></p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "</tbody>\n"
            + "</table>\n"
            + "</div>\n"
            + "\n";

    String TR_TABLE_TEMPLATE = "<h3>Scenarios </h3>\n"
            + "<table class=\"MsoNormalTable\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" "
            + "style=\"width:100.0%; background:#F6FFF2; border:outset black 1.0pt\">\n"
            + "<tbody>\n"
            + "<tr style=\"\">\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Status</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Scenario</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Time</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Causes</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Failed Steps</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "<td style=\"border:inset black 1.0pt; padding:1.5pt 1.5pt 1.5pt 1.5pt\">\n"
            + "<p class=\"MsoNormal\"><b><span style=\"font-size:9.0pt;\">Additional Information</span></b>\n"
            + "</p>\n"
            + "</td>\n"
            + "</tr>\n"
            + "${TEST_RUNS_ROWS}\n"
            + "</tbody>\n"
            + "</table>\n"
            + "\n"
            + "\n"
            + "</body></html>\n";
}
